### PR TITLE
Laravel 6 Support

### PR DESCRIPTION
**Pull request by darkhouse**
Minor changes to allow Laravel 6 support

### CODE REVIEW

**Comment by darkhouse** [comment]
The build config may need to be updated since this no longer works on php 7.1. I thought maybe adding the php 7.2 requirement would get the nightly one working, but apparently not.

**Comment by darkhouse** [comment]
OK, I clearly don't know how to get this working with the nightly builds. I'm going to stop trying. I'm wondering if that should even be included though at this point.

**Comment by alariva** [comment]
Thanks @darkhouse

I'll check it out as soon as possible

**Comment by alariva** [comment]
@darkhouse Please compare against https://github.com/alariva/laravel-email-domain-blacklist/compare/support-laravel-6 and provide a new squashed PR so I can marge with your authoring. Thanks again!

**Pull request closed without merging**
